baseURL = "https://eventhorizon-mtg.github.io/"
languageCode = "it-it"
title = "EventHorizon.mtg"

publishDir = "public"
canonifyURLs = false
enableRobotsTXT = true

[pagination]
  pagerSize = 12

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  article = "/articles/:slug/"

[params]
  siteName = "EventHorizon.mtg"
  appVer = "2025.09.27"

  # Open Graph (fallback globali; sovrascrivibili per pagina con front matter)
  [params.og]
    title = "EventHorizon.mtg"
    description = "Magic: The Gathering â€¢ Guide, video e risorse selezionate."
    image = "images/bg_image.webp"
    locale = "it_IT"

  # UI
  themeColor = "#0E0F1A"

  # Preload hero LCP (opzionale: lascia o cambia path)
  preloadHero = "images/bg_image.webp"

  # Fonts (self-hosted) preload list (WOFF2)
  [params.fonts]
    preload = [
      "fonts/LexendDeca-Regular.woff2",
      "fonts/LexendGiga-Regular.woff2",
      "fonts/Merriweather-Light.woff2",
      "fonts/OpenSans-Regular.woff2",
      "fonts/OpenSans-Italic.woff2"
    ]

[outputFormats.ArchiveList]
mediaType    = "application/json"
baseName     = "list"
isPlainText  = true
notAlternative = true
permalinkable  = true


relativeURLs = true




